// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2ppbv_no5FNxoPeBTJ6LW4UkywxL1VTE',
    appId: '1:234745350483:web:65fca5661aa9bcdbf4b9a6',
    messagingSenderId: '234745350483',
    projectId: 'chat-box-120af',
    authDomain: 'chat-box-120af.firebaseapp.com',
    storageBucket: 'chat-box-120af.appspot.com',
    measurementId: 'G-LL2FL7ZKFY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0dd7I51IwMBmsgu_wXxg5jK1DspX6ikE',
    appId: '1:234745350483:android:9c99e630bcc6b5e8f4b9a6',
    messagingSenderId: '234745350483',
    projectId: 'chat-box-120af',
    storageBucket: 'chat-box-120af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCogbO5q9LCzGs-hTLZc2_PoviGbRM4V8k',
    appId: '1:234745350483:ios:4abce53845f9964ff4b9a6',
    messagingSenderId: '234745350483',
    projectId: 'chat-box-120af',
    storageBucket: 'chat-box-120af.appspot.com',
    iosBundleId: 'com.example.chatBox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCogbO5q9LCzGs-hTLZc2_PoviGbRM4V8k',
    appId: '1:234745350483:ios:592d9ce007e7ad3ef4b9a6',
    messagingSenderId: '234745350483',
    projectId: 'chat-box-120af',
    storageBucket: 'chat-box-120af.appspot.com',
    iosBundleId: 'com.example.chatBox.RunnerTests',
  );
}
